### ISSUE TITLE
Typing lines in Basic interpreter resets badge

### ISSUE THREAD

**Issue by szczys** [Hack-a-Day/2018-Supercon-Badge#1]
Reproduce:

- Turn on badge
- Go to basic interpreter
- Type in `50 print a`
- Badge resets

**Comment by szczys** [comment]
Changing optimization from 's' to '1' fixed this reset error.

Right-click project --> Properties --> xc32-gcc --> Option Categories, select "Optimization" --> choose 1

**Comment by jaromir-sukuba** [comment]
Anyway, this is strange and shouldn't happen with higher optimizations. I'll take a look at this.
