### ISSUE TITLE
Default BASIC program triggers stack underflow

### ISSUE THREAD

**Issue by Roger-random** [Hack-a-Day/2018-Supercon-Badge#17]
Line "25 return" of default BASIC program triggers stack underflow error.

v116p.hex on Belgrade badge

Steps:
1. At main menu, press '1' to launch Hackaday BASIC
2. Type "run"
3. Observe stack underflow error.

![default basic stack underflow](https://user-images.githubusercontent.com/8559196/47637571-6af66c80-db19-11e8-8cf1-15d543df434f.jpg)

**Comment by jaromir-sukuba** [comment]
This is expected behavior. After returning from four nested subroutines, stack is empty, another return underflows the stack.

I recognize this to be default program in badge. This is my testing program I left there and badge should probably have something more sensible loaded by default.

**Comment by szczys** [comment]
Yes, I agree we need a default program for BASIC. Any suggestions?

-Mike Szczys
Editor in Chief
hackaday.com
hackaday.io
@szczys

**Comment by jaromir-sukuba** [comment]
There is still option of using demo from Belgrade badge.

**Comment by jaromir-sukuba** [comment]
From 1.17, code contains the previous demo, with url to supercon badge project page.

**Comment by Roger-random** [comment]
Confirm fixed in v1.18
Confirm updated URL points to the Hackaday.io project page for 2018 Supercon badge
