### ISSUE TITLE
Feature Proposal: Nyancat demo

### ISSUE THREAD

**Issue by Roger-random** [Hack-a-Day/2018-Supercon-Badge#19]
A fun demo of the badge's graphics and music playback capabilities via an adaptation of internet viral video 'nyancat'. Thanks to work done in v1.17 to clear up program memory, it is now possible to fit this demo on the default firmware. Code changes have been packaged as pull request #18. 

To launch: type "nya" from main menu. (This is expected to be changed.)

Commands: pressing '0' will mute music as animation continues. '9' will unmute.

Memory footprint: 84 bytes of data storage and 8676 bytes of program storage. Can be freed by not defining NYANCAT_DEMO in badge_settings.h.

**Comment by jaromir-sukuba** [comment]
This is piece of art, thanks for contributing.
I released 1.18 - just to keep with the numbering - with your code.

**Comment by Roger-random** [comment]
It was a lot of fun to write for the badge! Thanks for creating the foundation I could build upon.

Confirm nyancat demo (launched with 'nya') is integrated in 1.18.

**Comment by scottalmond** [comment]
This is beautiful
