### ISSUE TITLE
Where did the FORTH on the CPM disk, or the CPM in general, come from?

### ISSUE THREAD

**Issue by JamesNewton** [Hack-a-Day/2018-Supercon-Badge#21]
I'm trying to understand and document the FORTH that came on the badge under the CP/M. I've searched high and low and can't seem to find the source of either. As in source (where it came from) or source (source code). It is apparently fig-forth 1.1g for Z80. I was able to find a manual, in Hungarian, which I translated to English. But nothing else.

**Comment by hexagon5un** [comment]
I'll say that I did almost the same, but without the manual in Hungarian!  

I looked up some FIG  Forths, and had a play around.  Between the strange (to me) dialect and the all-caps, I was beaten and went back to BASIC.

**Comment by JamesNewton** [comment]
I've made some progress on it:
http://techref.massmind.org/techref/language/FORTH/z80fig-Forth1_1g.htm
