### ISSUE TITLE
Should libraries be optimized?

### ISSUE THREAD

**Issue by szczys** [Hack-a-Day/2018-Supercon-Badge#3]
When troublishooting #1 I changed library optimization from 1 to none since none is what we used for belgrade badge. Should this be optimized to 1, or left as none?

Poperties --> x32-ld --> Option Categories choose "libraries" --> Optimization Level of Standard Libraries

**Comment by jaromir-sukuba** [comment]
For this application it has no impact, it can be left as 'none'.
