### ISSUE TITLE
Badge freezes on Basic serial loading: 'sload' 

### ISSUE THREAD

**Issue by szczys** [Hack-a-Day/2018-Supercon-Badge#5]
In Basic interpreter type "sload". Badge cannot receive information and BRK has not effect.

**Comment by jaromir-sukuba** [comment]
I can't reproduce the issue. Both receiving from serial line and BRK abort does work as expected.
Please, try the 1.06 binary I just pushed to repository, it doesn't exhibit the problem. If the problem still persists, please paste build output here.

**Comment by szczys** [comment]
Tested and working in v1.07
